INSERT INTO product(id,
                    display_name,
                    short_description,
                    description,
                    category,
                    price,
                    discount,
                    delivery_charge,
                    offer_price,
                    seller_count,
                    avg_rating)
VALUES (1,
        'iPhone',
        'Smart Phone',
        'iPhone 10R',
        'Electronics',
        50000,
        5,
        0,
        475000,
        1,
        4.7);