spring:
  application:
    name: gateway-service


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 9999

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

jwt:
  secretKey: QnuQblQWn8H9ggiwfGbCxpPA3gdY1oAe
  key: QnuQblQWn8H9ggiwfGbCxpPA3gdY1oAe
  validityInMilliseconds: 1200000
