admin:
  username: superadmin
  password: superadmin
  status: Y

server:
  port: 0


spring:
  application:
    name: admin-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


  datasource:
    username: springuser
    password: ganga123
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ganga_admin_service
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
